name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}