name: Notify Discord on Push and Merge

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "**Action**: '${{ github.event_name }}'\n**Actor**: '${{ github.actor }}'\n**Branch**: '${{ github.ref_name }}'\n**Commit Message**: '${{ github.event.head_commit.message }}'}' \
          ${{ secrets.https://discord.com/api/webhooks/1319316217483366470/q_tjK_a6lo0cbKN7bluzlZirZ2lTW0RVJzR-zGfD-NPH55FGxwn3e7fUwuFXI2qWsvSH }}
