name: Notify Discord on Push and Merge

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        uses: tprobinson/discord-webhook@v2
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ${{ github.actor }} a effectué une action sur le dépôt :
            - **Action**: ${{ github.event_name }}
            - **Repository**: ${{ github.repository }}
            - **Branch**: ${{ github.ref_name }}
            - **Commit Message**: ${{ github.event.head_commit.message || 'N/A' }}
