name: Notify Discord on Push and Merge

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"**Repository**: ${{ github.repository }}\n**Action**: ${{ github.event_name }}\n**Actor**: ${{ github.actor }}\n**Branch**: ${{ github.ref_name }}\n**Commit Message**: ${{ github.event.head_commit.message || 'N/A' }}\"}" \
          "$DISCORD_WEBHOOK"
